apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-dev

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: microservice-config
  behavior: merge
  literals:
  - db_host=postgres-dev

secretGenerator:
- name: microservice-secrets
  literals:
  - db_user=postgres
  - db_password=dev-password